Customer/Pages/Order/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using CustomerSite.Helper;
using CustomerSite.Pages.Models;
using System.Text;
using SharedViewModels;

namespace CustomerSite.Pages;

public class OrderDetailModel : PageModel
{
    private APIHelper _api = new APIHelper();

    private readonly ILogger<OrderDetailModel> _logger;

    public OrderDetailModel(ILogger<OrderDetailModel> logger)
    {
        _logger = logger;
    }
    public decimal TotalPrice = 0;
    public List<OrderLineDTO> Cart = new List<OrderLineDTO>();
    public OrderDTO Order { get; set; } = default!;

    public async Task OnGetAsync(int? id)
    {
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Order/Get/{id}");
        var result = response.Content.ReadAsStringAsync().Result;
        Order = JsonConvert.DeserializeObject<OrderDTO>(result) ?? new OrderDTO();

        response = await client.GetAsync($"Order/GetCart/{id}");
        result = response.Content.ReadAsStringAsync().Result;
        Cart = JsonConvert.DeserializeObject<List<OrderLineDTO>>(result) ?? new List<OrderLineDTO>();
        foreach (var item in Cart)
        {
            TotalPrice += item.Quantity * item.Price;
        }
    }
}


Customer/Pages/Order/History.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using CustomerSite.Helper;
using CustomerSite.Pages.Models;
using System.Text;
using SharedViewModels;

namespace CustomerSite.Pages;

public class OrderHistoryModel : PageModel
{
    private APIHelper _api = new APIHelper();

    private readonly ILogger<OrderHistoryModel> _logger;

    public OrderHistoryModel(ILogger<OrderHistoryModel> logger)
    {
        _logger = logger;
    }
    [BindProperty]
    public List<OrderDTO> OrderHistory { get; set; } = null!;
    public async Task<IActionResult> OnGetAsync()
    {
        var session = HttpContext.Session;
        var UserId = session.GetString("Id");
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"User/OrderHistory/{UserId}");
        var result = response.Content.ReadAsStringAsync().Result;
        OrderHistory = JsonConvert.DeserializeObject<List<OrderDTO>>(result) ?? new List<OrderDTO>();

        return Page();
    }
}


Customer/Pages/Order/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using CustomerSite.Helper;
using CustomerSite.Pages.Models;
using System.Text;
using SharedViewModels;

namespace CustomerSite.Pages;

public class OrderModel : PageModel
{
    private APIHelper _api = new APIHelper();

    private readonly ILogger<OrderModel> _logger;

    public OrderModel(ILogger<OrderModel> logger)
    {
        _logger = logger;
    }

    public decimal TotalPrice = 0;
    public List<CartItem> Cart = new List<CartItem>();
    [BindProperty]
    public OrderDTO OrderForm { get; set; } = new OrderDTO();
    public async Task<IActionResult> OnGetAddToCartAsync(int id)
    {
        Cart = GetCartItems();
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Product/Read/{id}");
        var result = response.Content.ReadAsStringAsync().Result;
        var cartItem = JsonConvert.DeserializeObject<CartItem>(result) ?? new CartItem();
        var index = Cart.FindIndex(x => x.Id == cartItem.Id);
        if (index == -1)
        {
            cartItem.Quantity = 1;
            Cart.Add(cartItem);
        }
        else
        {
            Cart[index].Quantity++;
        }
        var session = HttpContext.Session;
        string jsoncart = JsonConvert.SerializeObject(Cart);
        session.SetString("cart", jsoncart);
        return RedirectToPage();
    }

    public void OnGet(int id)
    {
        Cart = GetCartItems();
        foreach (var item in Cart)
        {
            TotalPrice += item.Quantity * item.Price;
        }
    }

    public void OnGetClearCart(int id)
    {
        var session = HttpContext.Session;
        session.Remove("cart");
        Cart = new List<CartItem>();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var session = HttpContext.Session;
        var UserId = session.GetString("Id");
        OrderForm.UserId = UserId != null ? UserId : "";

        var token = session.GetString("AccessToken");
        if (token == null)
        {
            TempData["error"] = "You have to login first!";
            return RedirectToPage();
        }

        Cart = GetCartItems();

        if (Cart.Count == 0)
        {
            TempData["error"] = "Your cart is empty!";
            return RedirectToPage();
        }

        HttpClient client = _api.initial();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
        OrderForm.Cart = Cart.Select(x => new CartItemDTO { ProductId = x.Id, Quantity = x.Quantity }).ToList();
        var response = await client.PostAsJsonAsync("User/Order", OrderForm);
        var result = response.Content.ReadAsStringAsync().Result;

        if ((int)response.StatusCode != 200)
        {
            TempData["error"] = result;
            return RedirectToPage();
        }

        session.Remove("cart");
        Cart = new List<CartItem>();
        TempData["success"] = "Order Successfully";
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostUpdateOrderLine(int id, int quantity)
    {
        Cart = GetCartItems();

        var item = Cart.Find(s => s.Id == id);
        if (item == null)
            return RedirectToPage();
        if (quantity < 0)
        {
            TempData["error"] = "Quantity cannot be a negative number!";
            return RedirectToPage();
        }
        else if (quantity == 0)
            Cart = Cart.Where(x => x.Id != id).ToList();
        else
        {
            item.Quantity = quantity;
        }

        var session = HttpContext.Session;
        string jsoncart = JsonConvert.SerializeObject(Cart);
        session.SetString("cart", jsoncart);
        return RedirectToPage();
    }

    public List<CartItem> GetCartItems()
    {
        var session = HttpContext.Session;
        string jsoncart = session.GetString("cart")!;
        if (jsoncart != null)
        {
            return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart) ?? new List<CartItem>();
        }
        return new List<CartItem>();
    }
}


Customer/Pages/Products/Details.cshtml.cs
using Newtonsoft.Json;
using CustomerSite.Helper;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SharedViewModels;

namespace CustomerSite.Pages;
public class DetailsModel : PageModel
{
    private APIHelper _api = new APIHelper();
    private readonly ILogger<DetailsModel> _logger;

    public DetailsModel(ILogger<DetailsModel> logger)
    {
        _logger = logger;
    }

    public ProductDTO Product { get; set; } = default!;

    [BindProperty]
    public string Stars { get; set; } = "0";
    [BindProperty]
    public List<string> TitleList { get; set; } = new List<string>() { "Very Bad", "Poor", "OK", "Good", "Excellent" };
    [BindProperty]
    public ReviewFormDTO ReviewForm { get; set; } = default!;
    public List<RatingDTO> RatingList { get; set; } = new List<RatingDTO>();

    public async Task OnGetAsync(int? id)
    {
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Product/Read/{id}");
        var result = response.Content.ReadAsStringAsync().Result;
        Product = JsonConvert.DeserializeObject<ProductDTO>(result) ?? new ProductDTO();

        response = await client.GetAsync($"Rating/GetAll/{id}");
        result = response.Content.ReadAsStringAsync().Result;
        RatingList = JsonConvert.DeserializeObject<List<RatingDTO>>(result) ?? new List<RatingDTO>();
    }

    public async Task<IActionResult> OnPostAsync(int id)
    {
        ReviewForm.Star = Int32.Parse(Stars);
        if (ReviewForm.Star < 1 || ReviewForm.Star > 5)
        {
            TempData["error"] = "Click a star to rate!";
            return RedirectToPage();
        }

        ReviewForm.ProductId = id;

        var session = HttpContext.Session;
        ReviewForm.UserId = session.GetString("Id");

        var token = session.GetString("AccessToken");
        if (token == null)
        {
            TempData["error"] = "You have to login first!";
            return RedirectToPage();
        }

        HttpClient client = _api.initial();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var response = await client.PostAsJsonAsync("User/WriteReview", ReviewForm);
        var result = response.Content.ReadAsStringAsync().Result;

        if ((int)response.StatusCode != 200)
        {
            TempData["error"] = result;
            return RedirectToPage();
        }

        TempData["success"] = "Rating Successfully!";
        return RedirectToPage();
    }
}

Customer/Pages/Order/Detail.cshtml
@page "{id:int?}"
@model OrderDetailModel
@{
    ViewData["Title"] = "Order Detail";
}

<h1 class="text-center mt-5">Order Detail</h1>

<div class="container" style="margin-bottom: 200px;">
    <p><b>Your Order</b> at <em>@Model.Order.Time</em></p>
    <table class="table">
        <thead>
            <tr>
                <th class="w-50">PRODUCT</th>
                <th class="w-25">QUANTITY</th>
                <th class="w-25">PRICE</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.Cart)
            {
                <tr>
                    <td>
                        <div class="d-flex flex-column">
                            @if (@item.Image == "")
                            {
                                <img src="~/images/NoImage.png" style="width: 80px;" alt="">
                            }
                            else
                            {
                                <img src="~/images/@item.Image" style="width: 80px;" alt="">
                            }
                            <h6>@item.ProductName</h6>
                        </div>
                    </td>
                    <td class="align-middle">
                        @item.Quantity
                    </td>
                    <td class="align-middle">@item.Quantity X $@item.Price</td>
                </tr>
            }
            <tr>
                <td class="py-5">Total</td>
                <td colspan="2" class="text-center align-middle fw-bold">$@Model.TotalPrice</td>
            </tr>
        </tbody>
    </table>
</div>

Customer/Pages/Order/History.cshtml
@page
@model OrderHistoryModel
@{
    ViewData["Title"] = "Order History";
}

<h1 class="text-center mt-5">Order History</h1>
<p class="text-center mb-4">Click an order below to view in detail.</p>

<div class="container">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">Address</th>
                <th scope="col">Time</th>
            </tr>
        </thead>
        <tbody>
            @if (@Model.OrderHistory.Count < 1)
            {
                <tr>
                    <td colspan="2" class="text-center">You have not made any previous orders!</td>
                </tr>
            }
            else
            {
                @foreach (var order in @Model.OrderHistory)
                {
                    <tr onclick="Redirect(@order.Id)">
                        <td>@order.Address</td>
                        <td>@order.Time</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">
    function Redirect(id) {
        location.href = "/Order/Detail/" + id;
    }
</script>

Customer/Pages/Order/Index.cshtml
@page
@model OrderModel
@{
    ViewData["Title"] = "Order";
}

<h1 class="text-center mt-5">Your Order</h1>
<p class="text-center">If you are looking for a website to buy books online, NashBook is a great choice for you.</p>

<div class="container" style="margin-bottom: 200px;">
    <div class="d-flex justify-content-between">
        <p>You Have @Model.Cart.Count Items In Your Cart</p>
        <a asp-page="/Products/Index" style="text-decoration: none; color: #000;">Back to the Store</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="w-50">PRODUCT</th>
                <th class="w-20">QUANTITY</th>
                <th class="w-20">PRICE</th>
                <th class="w-10"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model.Cart)
            {

                <tr>
                    <td>
                        <div class="d-flex flex-column">
                            @if (item.Image == "")
                            {
                                <img src="~/images/NoImage.png" style="width: 80px;" alt="">
                            }
                            else
                            {
                                <img src="~/images/@item.Image" style="width: 80px;" alt="">
                            }
                            <h6>@item.Name</h6>
                        </div>
                    </td>
                    <td class="align-middle">
                        <form method="post" asp-page="./Index" asp-page-handler="UpdateOrderLine" asp-route-id="item.Id"
                        asp-route-quantity="@item.Quantity" class="d-flex">
                            <input hidden value="@item.Id" name="id">
                            <input asp-for="@item.Quantity" type="number" value="@item.Quantity" name="quantity"
                            class="form-control me-3" style="width: 80px;">
                            <button type="submit" class="btn btn-success">Update</button>
                        </form>
                    </td>
                    <td class="align-middle">@item.Quantity X $@item.Price</td>
                    <td class="align-middle text-end">
                        <form method="post" asp-page="./Index" asp-page-handler="UpdateOrderLine" asp-route-id="item.Id"
                        asp-route-quantity="@item.Quantity" class="d-flex">
                            <button type="submit" style="background: inherit; border: 0;">
                                <input hidden value="@item.Id" name="id">
                                <input hidden value=0 name="quantity">
                                <i class="bi bi-x" style="font-size: 30px;"></i>
                            </button>
                        </form>
                    </td>
                </tr>

            }
            <tr>
                <td class="py-5">Total</td>
                <td colspan="3" class="text-center align-middle fw-bold">$@Model.TotalPrice</td>
            </tr>
        </tbody>
    </table>
    <a class="btn btn-success" asp-page-handler="ClearCart">Clear Cart</a>

    <div class="info-form" style="margin-top: 40px;">
        <h4 style="border-bottom: 3px solid #e1e1e1;margin-bottom: 50px;" class="py-3">PLEASE FILL THE FORM!</h4>
        <form method="post" class="needs-validation">
            <input asp-for="@Model.OrderForm.Address" class="form-control mb-3" type="text" placeholder="Address"
                aria-label="default input example"
                style="border: 0; border-bottom: 2px solid #e1e1e1; border-radius: 0;" required>
            <div class="invalid-feedback">
                Please provide an address.
            </div>
            <input asp-for="@Model.OrderForm.Message" class="form-control mb-3" type="text" placeholder="Your message"
                aria-label="Your message" style="border: 0; border-bottom: 2px solid #e1e1e1; border-radius: 0;">
            <button class="btn btn-success my-4" type="submit" class="btn btn-success">Check Out</button>
        </form>
    </div>
</div>

Customer/Pages/Order/Success.cshtml
@page
@{
    ViewData["Title"] = "Order Sucess";
}

<h1 class="text-center mt-5">Order Sucessfully!</h1>