Customer/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomerSite.Models;

public class Product
{
    [Required]
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Image { get; set; }
    public string Author { get; set; } = string.Empty;
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }
    public int Quantity { get; set; }
    [DataType(DataType.Date)]
    public DateTime CreatedDate { get; set; }
    [DataType(DataType.Date)]
    public DateTime UpdatedDate { get; set; }
    public string? Category { get; set; }
}

Customer/Pages/Order/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using CustomerSite.Helper;
using CustomerSite.Pages.Models;
using System.Text;
using SharedViewModels;

namespace CustomerSite.Pages;

public class OrderDetailModel : PageModel
{
    private APIHelper _api = new APIHelper();

    private readonly ILogger<OrderDetailModel> _logger;

    public OrderDetailModel(ILogger<OrderDetailModel> logger)
    {
        _logger = logger;
    }
    public decimal TotalPrice = 0;
    public List<OrderLineDTO> Cart = new List<OrderLineDTO>();
    public OrderDTO Order { get; set; } = default!;

    public async Task OnGetAsync(int? id)
    {
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Order/Get/{id}");
        var result = response.Content.ReadAsStringAsync().Result;
        Order = JsonConvert.DeserializeObject<OrderDTO>(result) ?? new OrderDTO();

        response = await client.GetAsync($"Order/GetCart/{id}");
        result = response.Content.ReadAsStringAsync().Result;
        Cart = JsonConvert.DeserializeObject<List<OrderLineDTO>>(result) ?? new List<OrderLineDTO>();
        foreach (var item in Cart)
        {
            TotalPrice += item.Quantity * item.Price;
        }
    }
}


Customer/Pages/Order/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using CustomerSite.Helper;
using CustomerSite.Pages.Models;
using System.Text;
using SharedViewModels;

namespace CustomerSite.Pages;

public class OrderModel : PageModel
{
    private APIHelper _api = new APIHelper();

    private readonly ILogger<OrderModel> _logger;

    public OrderModel(ILogger<OrderModel> logger)
    {
        _logger = logger;
    }

    public decimal TotalPrice = 0;
    public List<CartItem> Cart = new List<CartItem>();
    [BindProperty]
    public OrderDTO OrderForm { get; set; } = new OrderDTO();
    public async Task<IActionResult> OnGetAddToCartAsync(int id)
    {
        Cart = GetCartItems();
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Product/Read/{id}");
        var result = response.Content.ReadAsStringAsync().Result;
        var cartItem = JsonConvert.DeserializeObject<CartItem>(result) ?? new CartItem();
        var index = Cart.FindIndex(x => x.Id == cartItem.Id);
        if (index == -1)
        {
            cartItem.Quantity = 1;
            Cart.Add(cartItem);
        }
        else
        {
            Cart[index].Quantity++;
        }
        var session = HttpContext.Session;
        string jsoncart = JsonConvert.SerializeObject(Cart);
        session.SetString("cart", jsoncart);
        return RedirectToPage();
    }

    public void OnGet(int id)
    {
        Cart = GetCartItems();
        foreach (var item in Cart)
        {
            TotalPrice += item.Quantity * item.Price;
        }
    }

    public void OnGetClearCart(int id)
    {
        var session = HttpContext.Session;
        session.Remove("cart");
        Cart = new List<CartItem>();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var session = HttpContext.Session;
        var UserId = session.GetString("Id");
        OrderForm.UserId = UserId != null ? UserId : "";

        var token = session.GetString("AccessToken");
        if (token == null)
        {
            TempData["error"] = "You have to login first!";
            return RedirectToPage();
        }

        Cart = GetCartItems();

        if (Cart.Count == 0)
        {
            TempData["error"] = "Your cart is empty!";
            return RedirectToPage();
        }

        HttpClient client = _api.initial();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
        OrderForm.Cart = Cart.Select(x => new CartItemDTO { ProductId = x.Id, Quantity = x.Quantity }).ToList();
        var response = await client.PostAsJsonAsync("User/Order", OrderForm);
        var result = response.Content.ReadAsStringAsync().Result;

        if ((int)response.StatusCode != 200)
        {
            TempData["error"] = result;
            return RedirectToPage();
        }

        session.Remove("cart");
        Cart = new List<CartItem>();
        TempData["success"] = "Order Successfully";
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostUpdateOrderLine(int id, int quantity)
    {
        Cart = GetCartItems();

        var item = Cart.Find(s => s.Id == id);
        if (item == null)
            return RedirectToPage();
        if (quantity < 0)
        {
            TempData["error"] = "Quantity cannot be a negative number!";
            return RedirectToPage();
        }
        else if (quantity == 0)
            Cart = Cart.Where(x => x.Id != id).ToList();
        else
        {
            item.Quantity = quantity;
        }

        var session = HttpContext.Session;
        string jsoncart = JsonConvert.SerializeObject(Cart);
        session.SetString("cart", jsoncart);
        return RedirectToPage();
    }

    public List<CartItem> GetCartItems()
    {
        var session = HttpContext.Session;
        string jsoncart = session.GetString("cart")!;
        if (jsoncart != null)
        {
            return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart) ?? new List<CartItem>();
        }
        return new List<CartItem>();
    }
}


Customer/Pages/Products/Details.cshtml.cs
using Newtonsoft.Json;
using CustomerSite.Helper;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SharedViewModels;

namespace CustomerSite.Pages;
public class DetailsModel : PageModel
{
    private APIHelper _api = new APIHelper();
    private readonly ILogger<DetailsModel> _logger;

    public DetailsModel(ILogger<DetailsModel> logger)
    {
        _logger = logger;
    }

    public ProductDTO Product { get; set; } = default!;

    [BindProperty]
    public string Stars { get; set; } = "0";
    [BindProperty]
    public List<string> TitleList { get; set; } = new List<string>() { "Very Bad", "Poor", "OK", "Good", "Excellent" };
    [BindProperty]
    public ReviewFormDTO ReviewForm { get; set; } = default!;
    public List<RatingDTO> RatingList { get; set; } = new List<RatingDTO>();

    public async Task OnGetAsync(int? id)
    {
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Product/Read/{id}");
        var result = response.Content.ReadAsStringAsync().Result;
        Product = JsonConvert.DeserializeObject<ProductDTO>(result) ?? new ProductDTO();

        response = await client.GetAsync($"Rating/GetAll/{id}");
        result = response.Content.ReadAsStringAsync().Result;
        RatingList = JsonConvert.DeserializeObject<List<RatingDTO>>(result) ?? new List<RatingDTO>();
    }

    public async Task<IActionResult> OnPostAsync(int id)
    {
        ReviewForm.Star = Int32.Parse(Stars);
        if (ReviewForm.Star < 1 || ReviewForm.Star > 5)
        {
            TempData["error"] = "Click a star to rate!";
            return RedirectToPage();
        }

        ReviewForm.ProductId = id;

        var session = HttpContext.Session;
        ReviewForm.UserId = session.GetString("Id");

        var token = session.GetString("AccessToken");
        if (token == null)
        {
            TempData["error"] = "You have to login first!";
            return RedirectToPage();
        }

        HttpClient client = _api.initial();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var response = await client.PostAsJsonAsync("User/WriteReview", ReviewForm);
        var result = response.Content.ReadAsStringAsync().Result;

        if ((int)response.StatusCode != 200)
        {
            TempData["error"] = result;
            return RedirectToPage();
        }

        TempData["success"] = "Rating Successfully!";
        return RedirectToPage();
    }
}

Customer/Pages/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using CustomerSite.Helper;
using SharedViewModels;

namespace CustomerSite.Pages;
public class ProductModel : PageModel
{
    private APIHelper _api = new APIHelper();
    private readonly ILogger<ProductModel> _logger;
    private readonly IConfiguration _configuration;

    public ProductModel(ILogger<ProductModel> logger, IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
    }

    public IEnumerable<ProductDTO>? Products = new List<ProductDTO>();
    public List<CategoryDTO>? Categories = new List<CategoryDTO>();
    [BindProperty(SupportsGet = true)]
    public string? SearchString { get; set; }
    public SelectList? OptionCategories { get; set; }
    [BindProperty(SupportsGet = true)]
    public string? SelectedCategory { get; set; }
    [BindProperty(SupportsGet = true)]
    public int CurrentPage { get; set; } = 1;
    [BindProperty(SupportsGet = true)]
    public int TotalPage { get; set; } = 0;
    // public PaginatedList<ProductDTO> paginatedProducts { get; set; } = null!;
    public async Task OnGetAsync(int pageIndex = 1)
    {
        HttpClient client = _api.initial();
        var response = await client.GetAsync($"Product/GetProducts?PageSize=4&PageNumber={pageIndex}");
        CurrentPage = pageIndex;
        Console.WriteLine(1111111111111111111);
        Console.WriteLine(pageIndex);
        var result = response.Content.ReadAsStringAsync().Result;

        Console.WriteLine(result);
        var pagingProduct = JsonConvert.DeserializeObject<PagedResponseModel<ProductDTO>>(result);

        TotalPage = pagingProduct == null ? 0 : Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(pagingProduct.TotalItems) / 4));
        Products = pagingProduct?.Items;

        response = await client.GetAsync("Category/GetAll");
        result = response.Content.ReadAsStringAsync().Result;
        Categories = JsonConvert.DeserializeObject<List<CategoryDTO>>(result);

        if (!string.IsNullOrEmpty(SearchString))
        {
            Products = Products!.Where(s => s.Name.ToLower().Contains(SearchString.ToLower())).ToList();
        }

        if (!string.IsNullOrEmpty(SelectedCategory))
        {
            Products = Products!.Where(x => x.CategoryName == SelectedCategory).ToList();
        }

        OptionCategories = new SelectList(Categories?.Select(x => x.Name));
    }
}

Customer/Pages/Products/Details.cshtml
@page "{id:int?}"
@model CustomerSite.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<div style="background: url('https://localhost:5001/images/Product/slider-bg.png') repeat; height: 300px;">
    <div class="container">
        <div>
            <img src="~/images/Product/inner-banner.png" alt="">
        </div>
    </div>
</div>

<div class="container" style="margin-top: 100px; margin-bottom: 150px;">
    <div class="card border-0 mb-5">
        <div class="row g-0">
            <div class="col-md-4 text-center">
                @if (@Model.Product.Image == "")
                {
                    <img src="~/images/NoImage.png" class="img-fluid rounded-start" alt="..."
                    style="width: 242px; height: 341px;">
                }
                else
                {
                    <img src="~/images/@Model.Product.Image" class="img-fluid rounded-start" alt="..."
                    style="width: 242px; height: 341px;">
                }
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: 700;">@Model.Product.Name</h5>
                    <p class="card-text">@Model.Product.Description</p>
                    <p class="card-text"><strong>Author:</strong> @Model.Product.Author</p>
                    <p class="card-text">Category: @Model.Product.CategoryName</p>
                    <p class="text-danger" style="font-size: 20px; font-weight: 500;">
                        $@Model.Product.Price
                    </p>
                    <div class="mb-3">
                        @for (int i = 0; i < Math.Round(@Model.Product.AverageRating * 2) / 2; i++)
                        {
                            <i class="bi bi-star-fill" style="color: #ffc700;"></i>
                        }
                        @if (Math.Round(@Model.Product.AverageRating * 2) % 2 == 1)
                        {
                            <i class="bi bi-star-half" style="color: #ffc700;"></i>
                        }
                        @for (int i = 0; i < Math.Floor((10 - Math.Round(@Model.Product.AverageRating * 2)) / 2); i++)
                        {
                            <i class="bi bi-star"></i>
                        }
                    </div>
                    <a class="btn btn-success" asp-page="../Order/Index" asp-page-handler="AddToCart"
                        asp-route-id="@Model.Product.Id">Add To Cart</a>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="card border-0" style="margin-top: 100px; margin-bottom: 100px;">
        <div class="row g-0">
            <div class="col-md-4">
                <h1 class="text-center"
                    style="font-weight: 750; font-size: 90px; transform: translateY(50px) rotate(-90deg);">Info</h1>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text"><strong>Format:</strong> @Model.Product.UpdatedDate</p>
                    <p class="card-text"><strong>Status:</strong>
                        @if (Model.Product.Quantity > 0)
                        {
                            <span> Available</span>
                        }
                        else
                        {
                            <span> Out of Stock</span>
                        }
                    </p>
                    <p class="card-text"><strong>Quantity:</strong> @Model.Product.Quantity</p>
                    <p class="card-text"><strong>Description:</strong> @Model.Product.Description
                    </p>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <h1 class="text-center text-danger" style="margin-top: 80px;">Write a Review</h1>
    <form method="post" style="font-size: 20px; margin-bottom: 100px;">
        <div class="d-flex justify-content-center">
            <div class="rate">
                @for (int i = 5; i > 0; i--)
                {
                    <input type="radio" id="@i" name="Stars" value=@i />
                    <label for="@i" title="text"></label>
                }
            </div>
        </div>
        <p class="text-center">Click a star to rate</p>
        <div class="form-floating mb-3">
            <textarea asp-for="@Model.ReviewForm.Comment" class="form-control" placeholder="Leave a comment here"
                id="floatingTextarea2" style="height: 100px"></textarea>
            <label for="floatingTextarea2">Comments</label>
        </div>
        <div class="d-flex justify-content-end">
            <button class="btn btn-success">Submit</button>
        </div>
    </form>

    <hr>

    <h1 style="margin-top: 50px;">Rating List</h1>

    @if (@Model.RatingList.Count == 0)
    {
        <div>
            No Comment Yet.
        </div>
    }
    @foreach (var rating in @Model.RatingList)
    {
        List<string> titles = new List<string>() { "Very Bad", "Poor", "Ok", "Good", "Excellent" };
        <div class="card mb-3">
            <div class="card-body">
                <div class='d-flex justify-content-between'>
                    <h5 class="card-title">
                        @if (rating.Star > 0 && rating.Star < 6)
                        {
                            @Model.TitleList[rating.Star-1]
                        }
                    </h5>
                    <p class="text-secondary">@rating.UpdatedDate</p>
                </div>
                <div class='d-flex justify-content-between'>
                    <span>
                        @for (int i = 0; i < rating.Star; i++)
                        {
                            <i class="bi bi-star-fill" style="color: #ffc700;"></i>
                        }
                        @for (int i = 0; i < 5 - rating.Star; i++)
                        {
                            <i class="bi bi-star"></i>
                        }

                    </span>
                    <p><span class="text-secondary">Written by </span>@rating.Reviewer</p>
                </div>
                <p class="card-text">@rating.Comment</p>
            </div>
        </div>
    }

</div>

<style>
    .rate {
        float: left;
        height: 46px;
        padding: 0 10px;
    }

    .rate:not(:checked)>input {
        position: absolute;
        top: -9999px;
    }

    .rate:not(:checked)>label {
        float: right;
        width: 1em;
        overflow: hidden;
        white-space: nowrap;
        cursor: pointer;
        font-size: 30px;
        color: #ccc;
    }

    .rate:not(:checked)>label:before {
        content: '★ ';
    }

    .rate>input:checked~label {
        color: #ffc700;
    }

    .rate:not(:checked)>label:hover,
    .rate:not(:checked)>label:hover~label {
        color: #deb217;
    }

    .rate>input:checked+label:hover,
    .rate>input:checked+label:hover~label,
    .rate>input:checked~label:hover,
    .rate>input:checked~label:hover~label,
    .rate>label:hover~input:checked~label {
        color: #c59b08;
    }
</style>

Customer/Pages/Products/Index.cshtml
@page
@model CustomerSite.Pages.ProductModel
@{
    ViewData["Title"] = "Product Page";
}

<div style="background: url('https://localhost:5001/images/Product/slider-bg.png') repeat; height: 300px;">
    <div class="container">
        <div>
            <img src="~/images/Product/inner-banner.png" alt="">
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-3">
            <form>
                <select asp-for="SelectedCategory" asp-items="Model.OptionCategories" class="form-select mb-3">
                    <option value="">All</option>
                </select>
                <div class="input-group flex-nowrap">
                    <input type="text" class="form-control" placeholder="Filter List..." aria-label="Search"
                        aria-describedby="addon-wrapping" asp-for="SearchString">
                    <button type="submit" class="input-group-text">
                        <i class="bi bi-search"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-9">
            <img src="~/images/Product/banner3.png" alt="">
            <div class="d-flex justify-content-between">
                <h1 class="d-flex align-middle my-3" style="font-weight: 700;">Books</h1>
                @* @{
                    var prevDisabled = !Model.paginatedProducts.HasPreviousPage ? "disabled" : "";
                    var nextDisabled = !Model.paginatedProducts.HasNextPage ? "disabled" : "";
                    }
                    <div class="d-flex align-items-center">
                    <a asp-page="./Index" asp-route-pageIndex="@(Model.paginatedProducts.PageIndex - 1)"
                    asp-route-SearchString="@Model.SearchString" class="btn btn-primary @prevDisabled">
                    Previous
                    </a>
                    <a asp-page="./Index" asp-route-pageIndex="@(Model.paginatedProducts.PageIndex + 1)"
                    asp-route-SearchString="@Model.SearchString" class="btn btn-primary ms-3 @nextDisabled">
                    Next
                    </a>
                    </div> *@

            </div>
            <div class="row" style="margin:20px 0px 110px 0px">
                @{
                    if (Model.Products != null)
                    {
                        foreach (var product in Model.Products)
                        {
                            <div class="col-3 d-flex align-items-stretch px-3">
                                <div class="card border-0" style="width: 100%;">
                                    <a asp-page="./Details" asp-route-id="@product.Id">
                                        @if (@product.Image == "")
                                        {
                                            <img src="~/images/NoImage.png" class="img card-img-top" alt="..." cover
                                style="object-fit: cover; height: 300px" />
                                        }
                                        else
                                        {
                                            <img src="~/images/@product.Image" class="img card-img-top" alt="..."
                                style="object-fit: cover; height: 300px" />
                                        }
                                    </a>
                                    <div class="card-body">
                                        <p class="card-title"
                                    style="font-weight: 500 !important; text-overflow: ellipsis; overflow: hidden; white-space: nowrap;">
                                            @product.Name</p>
                                        <p class="card-text mb-0"
                                    style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap;">
                                            <i>@product.Author</i>
                                        </p>
                                        <p class="card-text"
                                    style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap;">
                                            <i>@product.CategoryName</i>
                                        </p>
                                        <div class="mb-3">
                                            @for (int i = 0; i < Math.Floor(@product.AverageRating); i++)
                                            {
                                                <i class="bi bi-star-fill" style="color: #ffc700;"></i>
                                            }
                                            @if (Math.Round(@product.AverageRating * 2) % 2 == 1)
                                            {
                                                <i class="bi bi-star-half" style="color: #ffc700;"></i>
                                            }
                                            @for (int i = 0; i < Math.Floor((10 - Math.Round(@product.AverageRating * 2)) / 2); i++)
                                            {
                                                <i class="bi bi-star"></i>
                                            }
                                        </div>
                                        <p class="text-danger" style="font-size: 20px; font-weight: 500;">
                                            $@product.Price
                                        </p>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                }
                <nav aria-label="..." class="d-flex justify-content-end">
                    <ul class="pagination pagination-lg">
                        @{
                            for (int i = 1; i <= Model.TotalPage; i++)
                            {
                                <li class="page-item mx-1">
                                    <a asp-page="./Index" asp-route-pageIndex="@i" asp-route-SearchString="@Model.SearchString"
                                class="btn btn-primary">
                                        @i
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>